name: App CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - app/v[0-9]+\.[0-9]+\.[0-9]+
      - app/v[0-9]+\.[0-9]+\.[0-9]+-staging

  pull_request:
    branches:
      - main

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"
          cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache-dependency-path: go/package-lock.json
          cache: "npm"
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run build script
        run: ./scripts/build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: checkout-${{ github.run_id }}
          path: |
            ${{ github.workspace }}/
            !${{ github.workspace }}/go/node_modules

  build:
    needs: checkout
    name: Build
    uses: "./.github/workflows/build.yml"

  lint:
    needs: checkout
    name: Lint
    uses: "./.github/workflows/lint.yml"

  test:
    needs: checkout
    name: Test
    uses: ./.github/workflows/test.yml
